name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tayyhwork/hello-world-docker-action:latest
      
    - name: docker push
      run: |
        docker push tayyhwork/hello-world-docker-action
        
    - name: Tag the image
      run: |
        docker tag tayyhwork/hello-world-docker-action:latest tayyhwork/dct-demo-23:1
        docker push tayyhwork/dct-demo-23:1
                
    - name: Create Code Signing Certificate and Cert Key
      run: |
          echo "${{secrets.CERTIFICATE_KEY}}" > cert_key_23.key
          chmod 600 cert_key_23.key
          echo "${{secrets.CERTIFICATE}}" > cert_23.crt
          chmod 600 cert_23.crt         

          
    - name: Load the Cert key
      run: |
       docker trust key load cert_key_23.key --name dock_cert_key_23 <<-EOF
         ${{ secrets.CERTIFICATE_PASS }}
         ${{ secrets.CERTIFICATE_PASS }}
       EOF
       
    - name: Add signer
      run: |
        { echo '${{ secrets.CERTIFICATE_PASS }}';
          echo '${{ secrets.CERTIFICATE_PASS }}';
          sleep 15 && echo '${{ secrets.CERTIFICATE_PASS }}';
          echo '${{ secrets.CERTIFICATE_PASS }}';
        } | docker trust signer add --key cert_23.crt dock_cert_key_23 tayyhwork/dct-demo-23:1         

                
    - name: Tag the signed image
      run: |
       docker tag tayyhwork/dct-demo-23:1 tayyhwork/dct-demo-23:1-signed

    - name: Sign the image
      run: |
        docker trust sign tayyhwork/dct-demo-23:1-signed <<-EOF
         ${{ secrets.CERTIFICATE_PASS }}
         ${{ secrets.CERTIFICATE_PASS }}
         EOF     
        
    - name: Push the signed image
      run: |    
        docker push tayyhwork/dct-demo-23:1-signed
    - name: DCT On
      run: |      
        export DOCKER_CONTENT_TRUST=1  
      
    - name: Pull the unsigned image (fail) 
      run: |    
        docker pull tayyhwork/dct-demo-23:1    
    - name: DCT Off
      run: |      
        export DOCKER_CONTENT_TRUST=0 
      
    - name: Pull the unsigned image (pass)
      run: |    
        docker pull tayyhwork/dct-demo-23:1    
  
      
    - name: Upload image
      uses: ishworkh/docker-image-artifact-upload@v1
      with:
        image: tayyhwork/dct-demo-23:1-signed
        
        
    - name: Download image
      uses: ishworkh/docker-image-artifact-download@v1
      with:
        image: tayyhwork/dct-demo-23:1-signed

    - name: Link to the network drive
      run: |  
        sudo mkdir /TarDir
        sudo mount -t cifs //githubreporelstorage1.file.core.windows.net/sharefile /TarDir -o vers=3.0,username=githubreporelstorage1,password=${{ secrets.AZURE_PASS }},dir_mode=0777,file_mode=0777

    - name: Tar and copy the image for transferring
      run: | 
        docker save tayyhwork/dct-demo-23:1-signed | gzip > dct-demo-23:1-signed.tar.gz
        cp dct-demo-23:1-signed.tar.gz /TarDir
